language: python
sudo: false

python:
- 2.7

install:
- make install

script:
- make check

after_script:
- make deb
- openssl aes-256-cbc -K $encrypted_dd6e068c3ff6_key -iv $encrypted_dd6e068c3ff6_iv -in id_rsa.enc -out id_rsa -d
- chmod 0600 id_rsa
- scp -o StrictHostKeyChecking=no -i id_rsa thinkhazard_0.0_amd64.deb reprepro@pkg.camptocamp.net:/var/packages/apt/incoming
- ssh -o StrictHostKeyChecking=no -i id_rsa pkg.camptocamp.net '/usr/bin/reprepro -b /var/packages/apt includedeb /var/packages/apt/incoming/thinkhazard_0.0_amd64.deb'
