language: python
sudo: false

python:
- 2.7

install:
- make install

script:
- make check

after_script:
- (umask 066 && openssl aes-256-cbc -K $encrypted_dd6e068c3ff6_key -iv $encrypted_dd6e068c3ff6_iv -in id_rsa.enc -out id_rsa -d)
- ./deploy.sh
