language: python
sudo: false

python:
- 2.7

install:
- make install

script:
- make check

after_script:
- make deb
- gem install package_cloud
- package_cloud push raphink/test/debian/jessie/dev thinkhazard_0.0_amd64.deb
