language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/build/GFDRR/thinkhazard/.build/venv

python:
- 2.7

sudo: false

install:
- make install
- createuser www-data --no-superuser --no-createdb --no-createrole -U postgres
- createdb -O www-data thinkhazard_tests -U postgres
- psql -d thinkhazard_tests -c "CREATE EXTENSION postgis;" -U postgres


script:
- make check
- make build
- echo [app:main] >> local.tests.ini
- echo sqlalchemy.url = postgresql://www-data:www-data@localhost/thinkhazard_tests >> local.tests.ini
- .build/venv/bin/initialize_thinkhazard_db tests.ini
- make test
